title: Bradley Learns GitHub
author: bradleysa
email: bradley [ a t ] riseup dot not
description: > # this means to ignore newlines until "baseurl:"
  Spending time in the GitHub Learning Lab because learning new skills is always fun and rewarding.

# social links
twitter_username: bradleysa # DO NOT include the @ character, or else the build will fail!
github_username:  bradleysa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
